### ISSUE TITLE
ffplayout installation fails

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-frontend#36]
Hi !,
I re-installed ffplayout (I saw some changes have been made) - debian10  - but I encounter the following errors:
1) the install.sh file does not allow you to install nginx and ffmpeg as in previous versions; I therefore removed the following lines:
----------------------------------------------------------
if [[ "$(which ffmpeg 2>&1)" == *"which"* ]]; then
if [[ "$(which nginx 2>&1)" == *"which"* ]]; then
fi
fi
----------------------------------------------------------

2) at the end (after indicating user and psw) the installation fails (attachment)

<img width="684" alt="installation_error" src="https://user-images.githubusercontent.com/59960414/92999028-a3d53a00-f515-11ea-90bc-30772cbe5fc9.PNG">

can you help me ? thank you

**Comment by jb-alvarado** [comment]
Hi, the problem here is, that npm had no permission to install it dependencies. Temporary you could `chown -R root. /var/www` and later `chown -R www-data. /var/www`. 

But the problem is to, that I have restructure the repo, and spit it in two, so I have not one for the backend and one for the frontend. After that I have no test the install routine. My goal is, to dockerize ffplayout, but it takes a bit time to finish. Instead of the master branch it is more save at the moment to use the last release.

**Comment by chicco64** [comment]
sorry but don't work !
<img width="956" alt="ffplayout_error_13092020" src="https://user-images.githubusercontent.com/59960414/93021861-2b39b080-f5dd-11ea-9917-cd564e4a1cfd.PNG">

**Comment by jb-alvarado** [comment]
I fix some things, but could not test it much.

**Comment by chicco64** [comment]
ok thanks, i will try to retry the installation, i will let you know soon

**Comment by chicco64** [comment]
Hi !
installation done perfectly, everything seems ok, thanks !
