### ISSUE TITLE
Enhancments to the system

### ISSUE THREAD

**Issue by dfranje** [ffplayout/ffplayout-frontend#46]
Hello.  It would be great if some of the sugestions could be done.

1. Auto populate multiple days ( automaticly add all the videos from the opend folder to the timeline with a choosable option for auto adding ads after 1,2,3 video clips) 
2. Auto create xlmtv guide from playlist with clips name.
3. Auto add clips from another server ( remote source ) 
4. Multiple streams from same server. 

If you need assistance i am willing to pay a developer to contribute... Because i dont have the knowlage.

Keep up the excelente work

**Comment by jb-alvarado** [comment]
Hi, your number 4 is in progress, I need to see when I have time to finish it. Maybe next month.

Your other points are not so easy. Last year I created a in house playlist management software and I was also thinking to integrate it in ffplayout, but because it is to specific for our use case I decided to build a closed source external tool.

To make it good it needs a database and a really good concept about how to manage you media data. And I think it is almost impossible to have a solution what could use by a normal tv station, are music video station, or a church tv station. Everybody has his own work around and needs. 

ffplayout was planed as a simple playout solution, not so much as a media management nor playlist planer. The good thing is, that you can use or own playlist manager and transfer the playlist to ffplayout, that makes it more flexible.

I think you come cheaper when you search somebody how makes a playlist generator for you, exactly to your needs. This generator could talk to the ffplayout-api, for saving the playlists.

**Comment by jb-alvarado** [comment]
I create a new playlist [generator script](https://github.com/ffplayout/playlist-generator). Is very simple without logic, but you could use it as a starting point.

**Comment by dfranje** [comment]
> I create a new playlist [generator script](https://github.com/ffplayout/playlist-generator). Is very simple without logic, but you could use it as a starting point.

Thats great... Just what i need...  Can i set an argument in the script that an add video is inserted after every 1-2-3 video clips... And how should i aproach this?

**Comment by jb-alvarado** [comment]
You can use that script as an starting point to extend it to your needs.
