### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Marco-LB** [ffplayout/ffplayout-frontend#56]
is it possible to protect the media folder?
that is, is it possible to make sure that that folder is read only by an ip address?
I tried putting in an .htaccess file
"order deny, allow
deny from all
allow from <IP Adress>"
but unfortunately it doesn't work

**Comment by jb-alvarado** [comment]
Have currently access, to the media folder, outside from the frontend? Or do you want to have access?

Directory indexing can be realise by the [nginx server](https://www.keycdn.com/support/nginx-directory-index)

**Comment by Marco-LB** [comment]
if I point to the file name on the browser, for example:
ffplayout.com/media/sample.mp4 or ffplayout.com/tv-media/sample.mp4
I can see the file and download it.
I would like it to be accessible only to some ip addresses

**Comment by jb-alvarado** [comment]
This can be done to, in [nginx](https://stackoverflow.com/questions/22481408/restricting-access-to-files-and-directories-on-nginx-by-ip/22707581). The file to edit is: **/etc/nginx/sites-enabled/ffplayout.conf**. I think you need to add for that a new location.

**Comment by Marco-LB** [comment]
thank you so much!!!

**Comment by jb-alvarado** [comment]
There is a way to hide the URL with [**X-Accel-Redirect**](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/). I can put it to my ToDo, but it takes a bit time, because I need to integrate this in the API. 

Refs:

https://krzysztofzuraw.com/blog/2017/django-nginx-file-proxy-part-two
https://stackoverflow.com/questions/16189758/serve-large-file-with-php-and-nginx-x-accel-redirect
