### ISSUE TITLE
Installation for Windows OS?

### ISSUE THREAD

**Issue by DarkShadow45123** [ffplayout/ffplayout-frontend#63]
Is there any way to install the front end on windows?

**Comment by jb-alvarado** [comment]
No not out of the box.

The easiest way is to use windows subsystem for linux, or docker.

The frontend it self is not the problem, because its only about serving static files, but the other components are more difficult. You need a process manager, and both systemd and supervisord are not made for windows.

**Comment by DarkShadow45123** [comment]
ok thanks
