### ISSUE TITLE
Multi channel mode

### ISSUE THREAD

**Issue by JerryLutor** [ffplayout/ffplayout-frontend#92]
**Describe the bug**
When used in multi-channel mode, attempting to create and run another channel does not generate a configuration file.
When trying to delete a channel, a 500 error occurs.

**Server (please complete the following information):**
 - OS:  debian
 - Version  11

**Repo Version (please complete the following information):**
 - Version [e.g. v4.0.0]

**Additional context**
Is the multichannel mode supported at all now?

**Comment by jb-alvarado** [comment]
Thanks for report, I will look to it. Have you setup everything with the installer script, or by hand?

The future of multi-channel is not certain. It will most likely not be included in the next engine version. It's hard for me to maintain it, because it's not in use at my place and I have other priorities in development.

**Comment by jb-alvarado** [comment]
I created a new release from the API, where this should be fixed. If you want to update manually, replace **serializers.py** and **views.py** in folder `ffplayout/apps/api_player` with the one from repo.
